/*

    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

    Run time: 8.77ms

*/

use std::time::Instant;

fn main() {
    println!("\nQ: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n\n\t1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n\nBy considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.\n");

    let before = Instant::now();
    let mut sum: i32 = 0;
    let mut current_value = 1;
    let mut previous_value = 0;
    let mut new_value = 0;

    while new_value > 4000000 {
        let temp_current_value = current_value;
        new_value = current_value + previous_value;

        if (current_value + previous_value) % 2 == 0 {
            sum += new_value;
        }

        current_value = new_value;
        previous_value = temp_current_value;
    }

    println!("Answer: {}", sum);
    println!("Elapsed time: {:.2?}", before.elapsed());
}
