/*

    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/


fn main() {
    let mut sum: i32 = 0;
    let mut current_value = 1;
    let mut previous_value = 0;

    loop {
        let temp_current_value = current_value;
        let new_value = current_value + previous_value;

        if new_value > 4000000 {
            break;
        }

        if (current_value + previous_value) % 2 == 0 {
            sum += new_value;
        }

        current_value = new_value;
        previous_value = temp_current_value;
    }

    println!("{}", sum);
}
